# -*- coding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class DealStatus:
  """
   * Статус сделки
  *
  """
  STARTED = 1
  PRICE_ASKED = 2
  OFFERED = 3
  ACCEPTED = 4
  REJECTED = 5
  COMPLETED = 6

  _VALUES_TO_NAMES = {
    1: "STARTED",
    2: "PRICE_ASKED",
    3: "OFFERED",
    4: "ACCEPTED",
    5: "REJECTED",
    6: "COMPLETED",
  }

  _NAMES_TO_VALUES = {
    "STARTED": 1,
    "PRICE_ASKED": 2,
    "OFFERED": 3,
    "ACCEPTED": 4,
    "REJECTED": 5,
    "COMPLETED": 6,
  }

class DialogType:
  """
  Тип диалога, бывает двух видов

  """
  CHAT = 1
  DEAL = 2

  _VALUES_TO_NAMES = {
    1: "CHAT",
    2: "DEAL",
  }

  _NAMES_TO_VALUES = {
    "CHAT": 1,
    "DEAL": 2,
  }

class DealActivityState:
  """
   * Состояние сделки, где она лежит
  *
  """
  ARCHIVED = 1
  ACTIVE = 2

  _VALUES_TO_NAMES = {
    1: "ARCHIVED",
    2: "ACTIVE",
  }

  _NAMES_TO_VALUES = {
    "ARCHIVED": 1,
    "ACTIVE": 2,
  }

class SendMessageErrorStatus:
  """
  Ошибки посылки сообщений.

  """
  SENDING_DEAL_INTO_CHAT = 1
  WARE_OWNER_MISMATCH = 2
  NO_OFFER_YET = 3
  NO_ACCEPTANCE_YET = 4
  ALREADY_CLOSED = 5
  OFFER_CONDITION_MISMATCH = 6
  WARE_ID_MISMATCH = 7
  ALIEN_CHAT = 8
  PRICE_ALREADY_KNOWN = 9

  _VALUES_TO_NAMES = {
    1: "SENDING_DEAL_INTO_CHAT",
    2: "WARE_OWNER_MISMATCH",
    3: "NO_OFFER_YET",
    4: "NO_ACCEPTANCE_YET",
    5: "ALREADY_CLOSED",
    6: "OFFER_CONDITION_MISMATCH",
    7: "WARE_ID_MISMATCH",
    8: "ALIEN_CHAT",
    9: "PRICE_ALREADY_KNOWN",
  }

  _NAMES_TO_VALUES = {
    "SENDING_DEAL_INTO_CHAT": 1,
    "WARE_OWNER_MISMATCH": 2,
    "NO_OFFER_YET": 3,
    "NO_ACCEPTANCE_YET": 4,
    "ALREADY_CLOSED": 5,
    "OFFER_CONDITION_MISMATCH": 6,
    "WARE_ID_MISMATCH": 7,
    "ALIEN_CHAT": 8,
    "PRICE_ALREADY_KNOWN": 9,
  }

class DialogErrorStatus:
  DIALOG_NOT_FOUND = 1
  ALREADY_ARCHIVED = 2
  ALIEN_CHAT = 3

  _VALUES_TO_NAMES = {
    1: "DIALOG_NOT_FOUND",
    2: "ALREADY_ARCHIVED",
    3: "ALIEN_CHAT",
  }

  _NAMES_TO_VALUES = {
    "DIALOG_NOT_FOUND": 1,
    "ALREADY_ARCHIVED": 2,
    "ALIEN_CHAT": 3,
  }

