#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class ModerationState:
  BELIEVED = 1
  ACCEPTED = 2
  WAITING = 3
  BANNED = 4

  _VALUES_TO_NAMES = {
    1: "BELIEVED",
    2: "ACCEPTED",
    3: "WAITING",
    4: "BANNED",
  }

  _NAMES_TO_VALUES = {
    "BELIEVED": 1,
    "ACCEPTED": 2,
    "WAITING": 3,
    "BANNED": 4,
  }

class StockState:
  DRAFT = 1
  PUBLISHED = 2
  HIDDEN = 3
  ARCHIVE = 4
  DELETED = 5

  _VALUES_TO_NAMES = {
    1: "DRAFT",
    2: "PUBLISHED",
    3: "HIDDEN",
    4: "ARCHIVE",
    5: "DELETED",
  }

  _NAMES_TO_VALUES = {
    "DRAFT": 1,
    "PUBLISHED": 2,
    "HIDDEN": 3,
    "ARCHIVE": 4,
    "DELETED": 5,
  }

class WareRejectReason:
  PHOTO_BAD_VISIBILITY = 1
  PHOTO_STRANGE = 2
  POP_BRAND = 3
  OORRAA_RULES = 4
  PHOTO_LINKS = 5
  NOT_APPROVED = 6

  _VALUES_TO_NAMES = {
    1: "PHOTO_BAD_VISIBILITY",
    2: "PHOTO_STRANGE",
    3: "POP_BRAND",
    4: "OORRAA_RULES",
    5: "PHOTO_LINKS",
    6: "NOT_APPROVED",
  }

  _NAMES_TO_VALUES = {
    "PHOTO_BAD_VISIBILITY": 1,
    "PHOTO_STRANGE": 2,
    "POP_BRAND": 3,
    "OORRAA_RULES": 4,
    "PHOTO_LINKS": 5,
    "NOT_APPROVED": 6,
  }

class PriceChangeType:
  FIXED = 1
  PERCENT = 2
  AMOUNT = 3

  _VALUES_TO_NAMES = {
    1: "FIXED",
    2: "PERCENT",
    3: "AMOUNT",
  }

  _NAMES_TO_VALUES = {
    "FIXED": 1,
    "PERCENT": 2,
    "AMOUNT": 3,
  }

class PriceChangeResult:
  SUCCESS = 1
  FAIL = 2

  _VALUES_TO_NAMES = {
    1: "SUCCESS",
    2: "FAIL",
  }

  _NAMES_TO_VALUES = {
    "SUCCESS": 1,
    "FAIL": 2,
  }

