#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class RotationType:
  R90_DEGREES = 0
  R180_DEGREES = 1
  R270_DEGREES = 2

  _VALUES_TO_NAMES = {
    0: "R90_DEGREES",
    1: "R180_DEGREES",
    2: "R270_DEGREES",
  }

  _NAMES_TO_VALUES = {
    "R90_DEGREES": 0,
    "R180_DEGREES": 1,
    "R270_DEGREES": 2,
  }

class FileUploadFailure:
  RESOLUTION_TOO_SMALL = 1
  UNRECOGNIZED_TYPE = 2
  MALFORMED_DATA = 3
  SIZE_TOO_LARGE = 4
  UNSUPPORTED_TYPE = 5

  _VALUES_TO_NAMES = {
    1: "RESOLUTION_TOO_SMALL",
    2: "UNRECOGNIZED_TYPE",
    3: "MALFORMED_DATA",
    4: "SIZE_TOO_LARGE",
    5: "UNSUPPORTED_TYPE",
  }

  _NAMES_TO_VALUES = {
    "RESOLUTION_TOO_SMALL": 1,
    "UNRECOGNIZED_TYPE": 2,
    "MALFORMED_DATA": 3,
    "SIZE_TOO_LARGE": 4,
    "UNSUPPORTED_TYPE": 5,
  }

